package wormsmod.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

import org.lwjgl.opengl.GL11;

public class ModelAirPlane extends ModelBase{
    //fields
    ModelRenderer Base;
    ModelRenderer Wing1;
    ModelRenderer Wing2;
    ModelRenderer Wing3;
    ModelRenderer Wing4;
    ModelRenderer Cockpit;
    ModelRenderer Engine1;
    ModelRenderer Engine2;
    ModelRenderer Back;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer TailRotor;
    ModelRenderer RotorAxil;
    ModelRenderer MainRotor;
    ModelRenderer WheelAxil1;
    ModelRenderer WheelAxil2;
    ModelRenderer Wheel1;
    ModelRenderer WheelAxil3;
    ModelRenderer WheelAxil4;
    ModelRenderer Wheel2;
    ModelRenderer Nose1;
    ModelRenderer Nose2;
    ModelRenderer Nose3;
    ModelRenderer Nose4;

    public ModelAirPlane(){
        textureWidth = 128;
        textureHeight = 128;

        Base = new ModelRenderer(this, 0, 0);
        Base.addBox(0F, 0F, 0F, 14, 11, 23);
        Base.setRotationPoint(-7F, 6F, -11F);
        Base.setTextureSize(64, 32);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);
        Wing1 = new ModelRenderer(this, 0, 34);
        Wing1.addBox(0F, 0F, 0F, 9, 1, 6);
        Wing1.setRotationPoint(7F, 11F, -4F);
        Wing1.setTextureSize(64, 32);
        Wing1.mirror = true;
        setRotation(Wing1, 0F, 0F, 0F);
        Wing2 = new ModelRenderer(this, 0, 41);
        Wing2.addBox(0F, 0F, 0F, 9, 1, 6);
        Wing2.setRotationPoint(-16F, 11F, -4F);
        Wing2.setTextureSize(64, 32);
        Wing2.mirror = true;
        setRotation(Wing2, 0F, 0F, 0F);
        Wing3 = new ModelRenderer(this, 0, 48);
        Wing3.addBox(0F, 0F, 0F, 7, 1, 1);
        Wing3.setRotationPoint(7F, 11F, 2F);
        Wing3.setTextureSize(64, 32);
        Wing3.mirror = true;
        setRotation(Wing3, 0F, 0F, 0F);
        Wing4 = new ModelRenderer(this, 0, 50);
        Wing4.addBox(0F, 0F, 0F, 7, 1, 1);
        Wing4.setRotationPoint(-14F, 11F, 2F);
        Wing4.setTextureSize(64, 32);
        Wing4.mirror = true;
        setRotation(Wing4, 0F, 0F, 0F);
        Cockpit = new ModelRenderer(this, 0, 48);
        Cockpit.addBox(0F, 0F, 0F, 4, 2, 19);
        Cockpit.setRotationPoint(-2F, 4F, -9F);
        Cockpit.setTextureSize(64, 32);
        Cockpit.mirror = true;
        setRotation(Cockpit, 0F, 0F, 0F);
        Engine1 = new ModelRenderer(this, 0, 69);
        Engine1.addBox(0F, 0F, 0F, 4, 4, 10);
        Engine1.setRotationPoint(2F, 2F, -4F);
        Engine1.setTextureSize(64, 32);
        Engine1.mirror = true;
        setRotation(Engine1, 0F, 0F, 0F);
        Engine2 = new ModelRenderer(this, 0, 69);
        Engine2.addBox(0F, 0F, 0F, 4, 4, 10);
        Engine2.setRotationPoint(-6F, 2F, -4F);
        Engine2.setTextureSize(64, 32);
        Engine2.mirror = true;
        setRotation(Engine2, 0F, 0F, 0F);
        Back = new ModelRenderer(this, 0, 83);
        Back.addBox(0F, 0F, 0F, 10, 7, 3);
        Back.setRotationPoint(-5F, 8F, 12F);
        Back.setTextureSize(64, 32);
        Back.mirror = true;
        setRotation(Back, 0F, 0F, 0F);
        Tail1 = new ModelRenderer(this, 0, 93);
        Tail1.addBox(0F, 0F, 0F, 6, 3, 10);
        Tail1.setRotationPoint(-3F, 10F, 15F);
        Tail1.setTextureSize(64, 32);
        Tail1.mirror = true;
        setRotation(Tail1, 0F, 0F, 0F);
        Tail2 = new ModelRenderer(this, 0, 106);
        Tail2.addBox(0F, 0F, 0F, 2, 3, 8);
        Tail2.setRotationPoint(-1F, 10F, 23F);
        Tail2.setTextureSize(64, 32);
        Tail2.mirror = true;
        setRotation(Tail2, 0.7853982F, 0.0174533F, 0F);
        Tail3 = new ModelRenderer(this, 0, 117);
        Tail3.addBox(0F, 0F, 0F, 2, 3, 8);
        Tail3.setRotationPoint(-1.1F, 10F, 25F);
        Tail3.setTextureSize(64, 32);
        Tail3.mirror = true;
        setRotation(Tail3, -0.7853982F, 0.0174533F, 0F);
        TailRotor = new ModelRenderer(this, 74, 0);
        TailRotor.addBox(0F, -1.5F, -5F, 2, 3, 10);
        TailRotor.setRotationPoint(-5F, 11.5F, 24F);
        TailRotor.setTextureSize(64, 32);
        TailRotor.mirror = true;
        setRotation(TailRotor, 0F, 0F, 0F);
        RotorAxil = new ModelRenderer(this, 74, 13);
        RotorAxil.addBox(0F, 0F, 0F, 2, 4, 2);
        RotorAxil.setRotationPoint(-1F, 0F, 3F);
        RotorAxil.setTextureSize(64, 32);
        RotorAxil.mirror = true;
        setRotation(RotorAxil, 0F, 0F, 0F);
        MainRotor = new ModelRenderer(this, 74, 13);
        MainRotor.addBox(-1F, 0F, -12F, 2, 1, 24);
        MainRotor.setRotationPoint(0F, -1F, 4F);
        MainRotor.setTextureSize(64, 32);
        MainRotor.mirror = true;
        setRotation(MainRotor, 0F, 0F, 0F);
        WheelAxil1 = new ModelRenderer(this, 74, 38);
        WheelAxil1.addBox(0F, 0F, 0F, 2, 1, 1);
        WheelAxil1.setRotationPoint(-9F, 15F, -9F);
        WheelAxil1.setTextureSize(64, 32);
        WheelAxil1.mirror = true;
        setRotation(WheelAxil1, 0F, 0F, 0F);
        WheelAxil2 = new ModelRenderer(this, 74, 40);
        WheelAxil2.addBox(0F, 0F, 0F, 1, 3, 1);
        WheelAxil2.setRotationPoint(-9F, 16F, -9F);
        WheelAxil2.setTextureSize(64, 32);
        WheelAxil2.mirror = true;
        setRotation(WheelAxil2, 0F, 0F, 0F);
        Wheel1 = new ModelRenderer(this, 74, 44);
        Wheel1.addBox(0F, 0F, 0F, 1, 3, 3);
        Wheel1.setRotationPoint(-10F, 17F, -10F);
        Wheel1.setTextureSize(64, 32);
        Wheel1.mirror = true;
        setRotation(Wheel1, 0F, 0F, 0F);
        WheelAxil3 = new ModelRenderer(this, 74, 50);
        WheelAxil3.addBox(0F, 0F, 0F, 2, 1, 1);
        WheelAxil3.setRotationPoint(7F, 15F, -9F);
        WheelAxil3.setTextureSize(64, 32);
        WheelAxil3.mirror = true;
        setRotation(WheelAxil3, 0F, 0F, 0F);
        WheelAxil4 = new ModelRenderer(this, 74, 52);
        WheelAxil4.addBox(0F, 0F, 0F, 1, 3, 1);
        WheelAxil4.setRotationPoint(8F, 16F, -9F);
        WheelAxil4.setTextureSize(64, 32);
        WheelAxil4.mirror = true;
        setRotation(WheelAxil4, 0F, 0F, 0F);
        Wheel2 = new ModelRenderer(this, 74, 56);
        Wheel2.addBox(0F, 0F, 0F, 1, 3, 3);
        Wheel2.setRotationPoint(9F, 17F, -10F);
        Wheel2.setTextureSize(64, 32);
        Wheel2.mirror = true;
        setRotation(Wheel2, 0F, 0F, 0F);
        Nose1 = new ModelRenderer(this, 74, 62);
        Nose1.addBox(0F, 0F, 0F, 12, 9, 2);
        Nose1.setRotationPoint(-6F, 7F, -13F);
        Nose1.setTextureSize(64, 32);
        Nose1.mirror = true;
        setRotation(Nose1, 0F, 0F, 0F);
        Nose2 = new ModelRenderer(this, 74, 73);
        Nose2.addBox(0F, 0F, 0F, 10, 7, 2);
        Nose2.setRotationPoint(-5F, 8F, -15F);
        Nose2.setTextureSize(64, 32);
        Nose2.mirror = true;
        setRotation(Nose2, 0F, 0F, 0F);
        Nose3 = new ModelRenderer(this, 74, 82);
        Nose3.addBox(0F, 0F, 0F, 8, 5, 1);
        Nose3.setRotationPoint(-4F, 9F, -16F);
        Nose3.setTextureSize(64, 32);
        Nose3.mirror = true;
        setRotation(Nose3, 0F, 0F, 0F);
        Nose4 = new ModelRenderer(this, 74, 88);
        Nose4.addBox(0F, 0F, 0F, 5, 2, 1);
        Nose4.setRotationPoint(-2.5F, 10.5F, -17F);
        Nose4.setTextureSize(64, 32);
        Nose4.mirror = true;
        setRotation(Nose4, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5){
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Base.render(f5);
        Wing1.render(f5);
        Wing2.render(f5);
        Wing3.render(f5);
        Wing4.render(f5);
        Cockpit.render(f5);
        Engine1.render(f5);
        Engine2.render(f5);
        Back.render(f5);
        Tail1.render(f5);
        Tail2.render(f5);
        Tail3.render(f5);
        TailRotor.render(f5);
        RotorAxil.render(f5);
        MainRotor.render(f5);
        WheelAxil1.render(f5);
        WheelAxil2.render(f5);
        Wheel1.render(f5);
        WheelAxil3.render(f5);
        WheelAxil4.render(f5);
        Wheel2.render(f5);
        Nose1.render(f5);
        Nose2.render(f5);
        Nose3.render(f5);
        Nose4.render(f5);
    }

    public void renderModel(float size, float rotation){
        GL11.glTranslated(0, -20 / 16F, -0.5F);
        MainRotor.rotateAngleY = rotation;
        TailRotor.rotateAngleX = rotation;
        TailRotor.render(size);
        MainRotor.render(size);

        Base.render(size);
        Wing1.render(size);
        Wing2.render(size);
        Wing3.render(size);
        Wing4.render(size);
        Cockpit.render(size);
        Engine1.render(size);
        Engine2.render(size);
        Back.render(size);
        Tail1.render(size);
        Tail2.render(size);
        Tail3.render(size);
        RotorAxil.render(size);
        WheelAxil1.render(size);
        WheelAxil2.render(size);
        Wheel1.render(size);
        WheelAxil3.render(size);
        WheelAxil4.render(size);
        Wheel2.render(size);
        Nose1.render(size);
        Nose2.render(size);
        Nose3.render(size);
        Nose4.render(size);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z){
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
